version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

    commands:
      - n lts
  
  pre_build:
    commands:
      - aws ssm get-parameter --name "/parkingspace/frontend/enviroment" --output text  --query 'Parameter.Value' --with-decryption > .env.local

  build:
    commands:
      - npm i
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
